# Generated by Django 5.2.8 on 2025-11-12 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text="A unique name for the template (e.g., 'welcome_email')", max_length=200)),
                ('language', models.CharField(default='en', help_text="Language code for the template (e.g., 'en', 'es', 'fr')", max_length=10)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', help_text='Type of notification template', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Current version of the template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template version is active')),
                ('description', models.TextField(blank=True, help_text='Description of what this template is used for', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'language', '-version'],
                'indexes': [models.Index(fields=['name', 'language'], name='notificatio_name_dade11_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_878432_idx'), models.Index(fields=['template_type'], name='notificatio_templat_cb1a1b_idx')],
                'unique_together': {('name', 'language', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TemplateContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(blank=True, help_text='Subject line of the notification (can contain variables)', max_length=255, null=True)),
                ('body', models.TextField(help_text='The main content of the notification (can contain variables)')),
                ('extracted_variables', models.JSONField(blank=True, default=list, help_text='Automatically extracted variable names from subject and body.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='notification_templates.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRenderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('context_used', models.JSONField(help_text='Context variables used for rendering')),
                ('rendered_subject', models.TextField(blank=True, null=True)),
                ('rendered_body', models.TextField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, help_text='Service or user that requested the template', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_logs', to='notification_templates.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', 'created_at'], name='notificatio_templat_3decb0_idx'), models.Index(fields=['success', 'created_at'], name='notificatio_success_70b9f1_idx')],
            },
        ),
    ]
