# Generated by Django 5.2.8 on 2025-11-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecontent',
            name='is_html',
            field=models.BooleanField(default=True, help_text='Whether the body contains HTML content'),
        ),
    ]
