# Generated by Django 5.2.8 on 2025-12-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_templates', '0002_templatecontent_is_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification')], default='email', help_text='Type of notification template', max_length=20),
        ),
    ]
